# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{community}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["mkelley"]
  s.date = %q{2010-10-19}
  s.description = %q{A Rails 3 Forum Engine}
  s.email = %q{mike.reeves@atomos13.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "app/controllers/community/forums_controller.rb",
     "app/controllers/community/posts_controller.rb",
     "app/controllers/community/topics_controller.rb",
     "app/models/community/forum.rb",
     "app/models/community/posts.rb",
     "app/models/community/topic.rb",
     "app/views/community/forums/index.html.erb",
     "app/views/community/forums/show.html.erb",
     "app/views/community/topics/show.html.erb",
     "config/routes.rb",
     "lib/community.rb",
     "lib/engine.rb",
     "lib/rails/generators/community/install_generator.rb",
     "lib/rails/generators/community/templates/forums.rb",
     "lib/rails/generators/community/templates/posts.rb",
     "lib/rails/generators/community/templates/topics.rb",
     "lib/rails/railsties/tasks.rake"
  ]
  s.homepage = %q{http://github.com/mkelley/community}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A Rails 3 Forum Engine}
  s.test_files = [
    "test/helper.rb",
     "test/test_community.rb"
  ]
end

