# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{community}
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gitt"]
  s.date = %q{2010-11-14}
  s.description = %q{A Rails 3 Forum Engine}
  s.email = %q{mike.reeves@atomos13.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "app/controllers/community/forums_controller.rb",
    "app/controllers/community/posts_controller.rb",
    "app/controllers/community/topics_controller.rb",
    "app/models/community/forum.rb",
    "app/models/community/topic.rb",
    "app/views/community/forums/_form.html.erb",
    "app/views/community/forums/edit.html.erb",
    "app/views/community/forums/index.html.erb",
    "app/views/community/forums/new.html.erb",
    "app/views/community/forums/show.html.erb",
    "app/views/community/posts/_form.html.erb",
    "app/views/community/posts/edit.html.erb",
    "app/views/community/posts/new.html.erb",
    "app/views/community/topics/_form.html.erb",
    "app/views/community/topics/edit.html.erb",
    "app/views/community/topics/new.html.erb",
    "app/views/community/topics/show.html.erb",
    "config/routes.rb",
    "lib/acts_as_community_member/base.rb",
    "lib/application_helper.rb",
    "lib/community.rb",
    "lib/engine.rb",
    "lib/rails/generators/community/install_generator.rb",
    "lib/rails/generators/community/templates/migrations/forums.rb",
    "lib/rails/generators/community/templates/migrations/posts.rb",
    "lib/rails/generators/community/templates/migrations/topics.rb",
    "lib/rails/generators/community/templates/migrations/user.rb",
    "lib/rails/generators/community/templates/models/post.rb",
    "lib/rails/generators/community/templates/models/topic.rb",
    "lib/rails/generators/community/views_generator.rb",
    "lib/rails/railsties/tasks.rake",
    "public/images/ruby.png",
    "public/stylesheets/community.css"
  ]
  s.homepage = %q{http://github.com/mkelley/community}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A Rails 3 Forum Engine}
  s.test_files = [
    "test/helper.rb",
    "test/test_community.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

